- hosts: test

  pre_tasks:
    - include: tasks/base.yml tags=base
    - set_fact:
        build_ncores: "{{ ansible_processor_vcpus }}"
      when: build_ncores is undefined

  roles:
    - {role: casalibs-src, casalibs_build_ncores: "{{build_ncores}}" }


  tasks:

    - name: Create install dir and repo dir with correct permissions
      file: path={{ item }} state=directory mode=0755 owner={{ansible_user_id}}
      with_items:
        - repo_dir
        - default_install_prefix
      sudo: yes

    - include: tasks/check-casalibs-ok.yml tags=test
      vars:
        casalibs_install_prefix: "{{ hostvars['test']['casalibs_install_prefix']}}"
    - include: tasks/install-tkp-apt-deps.yml tags=tkp
    - include: tasks/install-lofim-apt-deps.yml tags=lofim
    - include: tasks/install-lofim.yml tags=lofim
    - include: tasks/install-aoflagger.yml tags=aoflagger

