- name: Check casalibs import OK
  shell: >
          . {{casalibs_install_prefix}}/init-casalibs.sh &&
            python -c "from casacore import measures,tables; print('A-OK');"
  changed_when: False
  tags: test