- name: Install LOFAR apt dependencies
  apt: name={{item}} update_cache=yes cache_valid_time=600
  with_items: "{{ lookup('file', 'files/lofar-apt-deps-ubuntu-12.04-14.04.txt').split() }}"
  sudo: yes
  tags: apt
